### PR TITLE
Fix ellipses so we can draw to left or upward

### LINKED ISSUE #4: You can only create a circle by dragging down to the right but not in any of the other directions
http://concord-consortium.github.io/drawing-tool/examples/

### PR DESCRIPTION
**Pull request by sfentress**
Fixes #4 .

### CODE REVIEW

File: app/scripts/tools/shape-tools/basic-shape-tool.js [hunk 1]
```diff
@@ -71,15 +74,18 @@ BasicShapeTool.prototype.mouseMove = function (e) {
     }
   }
 
-  this.curr.set({
+  // we have to convert to positive dimensions as we draw, as ellipises cannot handle negative radii.
```
Comment (kswenson) [inline app/scripts/tools/shape-tools/basic-shape-tool.js:77]:
```suggestion
  // we have to convert to positive dimensions as we draw, as ellipses cannot handle negative radii.
```
